command = '/home/devops/LMS-Education-system/venv/bin/gunicorn'
pythonpath = '/home/devops/LMS-Education-system'
bind = '127.0.0.1:8000'
workers = 8
threads = 4
user = 'devops'
limit_request_fields = 32000
limit_request_field_size = 0
raw_env = 'DJANGO_SETTINGS_MODULE=config.settings'
